// prisma/seed/seedArtistes.ts
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export async function seedArtistes() {
  console.log('Seeding artistes…');
  await prisma.artiste.createMany({
    data: [
      {
        id_artiste: 2,
        nom_artiste: 'Kahlo',
        prenom_artiste: 'Frida',
        pays_artiste: 'Mexique',
        date_naissance_artiste: '1907-07-06',
        site_web_artiste: 'https://fridakahlo.org',
        url_image_artiste_1: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746710508/artiste_mexique_1.jpg',
        url_image_artiste_2: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746710505/artiste_mexique_2.jpg',
        url_image_artiste_3: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746710456/artiste_mexique_3.jpg',
        description_artiste_1: 'Frida Kahlo est une peintre mexicaine emblématique du XXᵉ siècle, reconnue pour ses autoportraits intenses et son style mêlant réalisme et éléments surréalistes. Son œuvre profondément personnelle puise dans sa vie, sa culture et ses douleurs pour créer des images puissantes et inoubliables.',
        description_artiste_2: 'Née en 1907 à Coyoacán, Frida fait face à la poliomyélite puis à un grave accident d’autobus qui l’immobilise et la pousse à peindre pendant sa convalescence. Mariée au muraliste Diego Rivera, elle intègre le cercle des avant-gardes mexicaines et expose dès les années 1930 à Mexico, New York et Paris, affirmant son talent et sa singularité.',
        description_artiste_3: 'Animée par la célébration de l’identité mexicaine, la résilience face à l’adversité et la défense des droits des femmes, Frida incarne la force et l’authenticité. Son engagement politique et sa vision de l’art comme acte de mémoire et de résistance continuent d’inspirer des générations d’artistes à travers le monde.',
        url_instagram_reseau_social: '@frida_kahlo',
        url_tiktok_reseau_social: '@frida.art',
      },
      {
        id_artiste: 3,
        nom_artiste: 'Basquiat',
        prenom_artiste: 'Jean-Michel',
        pays_artiste: 'États-Unis',
        date_naissance_artiste: '1960-12-22',
        site_web_artiste: 'https://basquiat.com',
        url_image_artiste_1: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746709082/artiste_usa_1.jpg',
        url_image_artiste_2: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746709079/artiste_usa_2.jpg',
        url_image_artiste_3: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746709078/artiste_usa_3.jpg',
        description_artiste_1: 'Jean-Michel Basquiat est un peintre et plasticien américain pionnier de la scène underground new-yorkaise des années 1980. Passant du graffiti à la galerie, il a su imposer un style brut et poétique, mêlant textes, symboles et imagerie urbaine.',
        description_artiste_2: 'Né le 22 décembre 1960 à Brooklyn, Basquiat fait ses débuts sous le pseudonyme SAMO avant d’attirer l’attention d’Andy Warhol. Rapidement exposé à New York, Paris et Tokyo, il signe des toiles mêlant abstraction et figuration où se racontent ses origines haïtiennes et porto-ricaines.',
        description_artiste_3: 'Porté par la dénonciation des inégalités raciales et sociales, Basquiat défend la mémoire culturelle afro-américaine et l’émancipation par l’art. Son engagement pour la justice et sa liberté créative continuent d’inspirer artistes et militants du monde entier.',
        url_instagram_reseau_social: '@basquiat_legacy',
        url_tiktok_reseau_social: '@basquiat.art',
      },
      {
        id_artiste: 6,
        nom_artiste: 'Rossi',
        prenom_artiste: 'Luca',
        pays_artiste: 'Italie',
        date_naissance_artiste: '1985-03-15',
        site_web_artiste: 'https://lucarossi-art.it',
        url_image_artiste_1: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746709076/artiste_italie_1.jpg',
        url_image_artiste_2: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746709076/artiste_italie_3.jpg',
        url_image_artiste_3: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746709082/artiste_italie_2.jpg',
        description_artiste_1: 'Luca Rossi est un artiste milanais né en 1985, reconnu comme l’un des pionniers du street art moderne en Italie. Son travail consacre l’espace urbain comme support de création, mêlant fresques monumentales et interventions éphémères qui surprennent et questionnent le regard.',
        description_artiste_2: 'Formé à l’Académie de Brera, Luca a affiné son style entre la tradition picturale italienne et les techniques contemporaines. Ses œuvres, exposées à Milan, Rome et Barcelone, se caractérisent par un équilibre subtil entre motifs géométriques, palettes vives et jeux d’ombre, créant une nouvelle lecture des façades et des places publiques.',
        description_artiste_3: 'Porté par des valeurs de partage et de durabilité, Luca collabore avec des associations locales pour transformer des quartiers en galeries à ciel ouvert. Ses projets visent à renforcer le lien social et à promouvoir l’innovation artistique tout en respectant l’environnement et la mémoire collective des lieux.',
        url_instagram_reseau_social: '@lucarossi_art',
        url_tiktok_reseau_social: '@luca.rossi',
      },
      {
        id_artiste: 5,
        nom_artiste: 'Druck',
        prenom_artiste: 'Jean-Michel',
        pays_artiste: 'Argentine',
        date_naissance_artiste: '1960-12-22',
        site_web_artiste: 'https://basquiat.com',
        url_image_artiste_1: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746712079/artiste_argentine_1.jpg',
        url_image_artiste_2: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746709075/artiste_argentine_2.jpg',
        url_image_artiste_3: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746709075/artiste_argentine_3.jpg',
        description_artiste_1: 'Jean-Michel Druck est un artiste argentin dont l’univers pictural puise dans la richesse culturelle de Buenos Aires. À travers ses toiles vibrantes, il tisse un dialogue entre les traditions sud-américaines et une esthétique contemporaine, affirmant dès ses premières œuvres une voix singulière sur la scène artistique internationale.',
        description_artiste_2: 'Né en 1960 dans le quartier de La Boca, Druck suit des études aux Beaux-Arts de l’Université de Buenos Aires avant de voyager en Europe pour parfaire son style. Ses créations, mêlant peinture acrylique, collages photographiques et interventions graphiques, ont été exposées à São Paulo, Madrid et New York, où elles ont été saluées pour leur énergie urbaine et leur capacité à raconter des histoires de mémoire et d’identité.',
        description_artiste_3: 'Porté par des valeurs d’engagement social et d’écologie, Druck utilise l’art comme vecteur de transformation : il soutient des projets de réhabilitation de quartiers défavorisés et milite pour la préservation des savoir-faire locaux. Son travail incarne la résilience et la solidarité, faisant de chaque toile un appel à la rencontre entre les cultures et à la responsabilité collective.',
        url_instagram_reseau_social: '@basquiat_legacy',
        url_tiktok_reseau_social: '@basquiat.art',
      },
      {
        id_artiste: 1,
        nom_artiste: 'Ahjam',
        prenom_artiste: 'Sarah',
        pays_artiste: 'Algérie',
        date_naissance_artiste: '1904-05-11',
        site_web_artiste: 'https://dali.com',
        url_image_artiste_1: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746709075/artiste_algeria_1.jpg',
        url_image_artiste_2: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746709082/artiste_algeria_2.jpg',
        url_image_artiste_3: 'https://res.cloudinary.com/dpwuvu0k3/image/upload/v1746687328/artiste_algeria_3.jpg',
        description_artiste_1: 'Sarah Ahjam est une artiste contemporaine algérienne dont le travail mêle traditions visuelles du Maghreb et esthétiques avant-gardistes. À travers ses toiles vibrantes, elle rend hommage à son héritage culturel tout en explorant de nouvelles formes d’expression.',
        description_artiste_2: 'Née à Alger, Sarah a suivi un cursus aux Beaux-Arts avant de s’installer en Europe pour parfaire sa technique. Son œuvre, oscillant entre abstraction et figuration, a été exposée à Paris, Berlin et New York, et fait écho aux enjeux d’identité et de mémoire collective.',
        description_artiste_3: 'Animée par la solidarité, le respect de l’environnement et la valorisation des talents émergents, Sarah collabore avec plusieurs associations pour promouvoir l’art durable et inclusif. Elle considère chaque création comme un pont entre les cultures et les générations.',
        url_instagram_reseau_social: '@dali_art',
        url_tiktok_reseau_social: '@dali.tok',
      },
    ],
    skipDuplicates: true,
  });
}
