###GET client ok
GET http://localhost:1992/api/auth

###
////////////////////////////////////////////////////////

###GET client particulier ok
GET http://localhost:1337/api/auth/1
Content-Type: application/json

###
////////////////////////////////////////////////////////

###POST client
POST http://localhost:1992/api/auth/register
Content-Type: application/json

{
    "data": {
        "nom_client": "Sabristi",
        "prenom_client": "sabristi88",
        "civilite": "femme",
        "date_naissance_client": "1993-10-09T00:00:00.000Z",
        "adresse_client": "15 rue des Roses",
        "code_postal_client": "38100",
        "ville_client": "Grenoble",
        "pays_client": "France",
        "mot_de_passe": "mtp",
        "adresse_mail_client": "sab@gmail.com"
    }
}
###
////////////////////////////////////////////////////////

###PUT client
PUT http://localhost:1992/api/auth/3
Content-Type: application/json

{
    "data": {

    }
}

###
////////////////////////////////////////////////////////

###DELETE client particulier
DELETE http://localhost:1992/api/auth/3
Content-Type: application/json

