###GET client ok
GET http://localhost:1992/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjMsImVtYWlsIjoiZGFsaWxhQGdtYWlsLmNvbSIsImlhdCI6MTc0NTA5MjY4MiwiZXhwIjoxNzQ1MTc5MDgyfQ.nSJq-sJmLczJkjokmh8ud2RWzPxcm20c7npQ7cMkC9g

###
////////////////////////////////////////////////////////

###GET client particulier ok
GET http://localhost:1992/api/auth/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjMsImVtYWlsIjoiZGFsaWxhQGdtYWlsLmNvbSIsImlhdCI6MTc0NTA5MjY4MiwiZXhwIjoxNzQ1MTc5MDgyfQ.nSJq-sJmLczJkjokmh8ud2RWzPxcm20c7npQ7cMkC9g

###
////////////////////////////////////////////////////////

###POST client
POST http://localhost:1992/api/auth/register
Content-Type: application/json

{
    "data": {
        "nom_client": "Hammadi",
        "prenom_client": "Sabrinaaa",
        "civilite": "femme",
        "date_naissance_client": "",
        "adresse_client": "",
        "code_postal_client": "",
        "ville_client": "",
        "pays_client": "",
        "mot_de_passe": "",
        "adresse_mail_client": ""
    }
}
###
////////////////////////////////////////////////////////

###PUT client
PUT http://localhost:1992/api/auth/8
Content-Type: application/json
Authorization: Bearer 

{
    "data": {
        "id_role": 2
    }
}

###
////////////////////////////////////////////////////////

###DELETE client particulier
DELETE http://localhost:1992/api/auth/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjMsImVtYWlsIjoiZGFsaWxhQGdtYWlsLmNvbSIsImlhdCI6MTc0NTA5MjY4MiwiZXhwIjoxNzQ1MTc5MDgyfQ.nSJq-sJmLczJkjokmh8ud2RWzPxcm20c7npQ7cMkC9g

