### GET toutes les associations
GET http://localhost:1992/api/association

### GET association par ID
GET http://localhost:1992/api/association/4
Content-Type: application/json

### POST association
POST http://localhost:1992/api/association/create
Content-Type: application/json

{
  "data": {
    "id_maillot_association": 4,
    "nom_association": "UNICEF",
    "numero_identification_association": "UN123456",
    "adresse_siege_social_association": "12 rue des enfants",
    "pays_association": "France",
    "site_web_association": "https://unicef.fr",
    "url_image_association_1": "unicef1.jpg",
    "url_image_association_2": "unicef2.jpg",
    "url_image_association_3": "unicef3.jpg",
    "description_association_1": "Organisation humanitaire mondiale",
    "description_association_2": "Protection de l'enfance",
    "description_association_3": "Aide d'urgence"
  }
}

### PUT association
PUT http://localhost:1992/api/association/4
Content-Type: application/json

{
  "data": {
    "description_association_1": "Modifiée pour test"
  }
}

### DELETE association
DELETE http://localhost:1992/api/association/4
