###POST Reparation
POST http://localhost:1992/api/reparations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwc2V1ZG8iOiJTYWJyaXN0aSIsImlhdCI6MTczODg0ODE3OH0.8DIfYw4uYG-U8YkmrcOSMvIZMU_arLyOpUeoKePz2k8


{
    "data": {
        "name":"Repartion des touches",
        "prix":150,
        "instrumentId":1
    }
}
###
////////////////////////////////////////////////////////

###DELETE Reparation 
DELETE http://localhost:1992/api/reparations/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwc2V1ZG8iOiJTYWJyaXN0aSIsImlhdCI6MTczODg0ODE3OH0.8DIfYw4uYG-U8YkmrcOSMvIZMU_arLyOpUeoKePz2k8

