###GET Token
GET http://localhost:1992/api/tokens
////////////////////////////////////////////////////////

###GET Token particulier
GET http://localhost:1992/api/tokens/cm8lb76k20000fl02pt9vmwzt
Content-Type: application/json
////////////////////////////////////////////////////////

###POST Token
POST http://localhost:1992/api/tokens
Content-Type: application/json

{
    "data": {

    }
}
////////////////////////////////////////////////////////

###PUT Token
PUT http://localhost:1992/api/tokens/2
Content-Type: application/json

{
    "data": {
        "valeur_token": "nouveau_token",
        "expiration": "2025-04-22T12:00:00Z"
    }
}
////////////////////////////////////////////////////////

###DELETE User particulier
DELETE http://localhost:1992/api/tokens/cm8lb76k20000fl02pt9vmwzt
Content-Type: application/json
////////////////////////////////////////////////////////
