### GET toutes les TVA
GET http://localhost:1992/api/tva

### GET TVA par ID
GET http://localhost:1992/api/tva/1

### POST TVA (admin)
POST http://localhost:1992/api/tva/create
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}
{
  "data": {
    "taux_tva": 5,
    "description_tva": "TVA réduite pour UE"
  }
}

### PUT TVA (admin)
PUT http://localhost:1992/api/tva/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjMsImVtYWlsIjoiZGFsaWxhQGdtYWlsLmNvbSIsImlhdCI6MTc0NTA5MjY4MiwiZXhwIjoxNzQ1MTc5MDgyfQ.nSJq-sJmLczJkjokmh8ud2RWzPxcm20c7npQ7cMkC9g


{
  "data": {
    "taux_tva": 20,
    "description_tva": "TVA standard France (mise à jour)"
  }
}

### DELETE TVA (admin)
DELETE http://localhost:1992/api/tva/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjMsImVtYWlsIjoiZGFsaWxhQGdtYWlsLmNvbSIsImlhdCI6MTc0NTA5MjY4MiwiZXhwIjoxNzQ1MTc5MDgyfQ.nSJq-sJmLczJkjokmh8ud2RWzPxcm20c7npQ7cMkC9g

