### ✅ GET - Toutes les commandes de l’utilisateur connecté
GET http://localhost:1992/api/commande
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjgsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpZF9yb2xlIjoyLCJpYXQiOjE3NDU1NTgyMzksImV4cCI6MTc0NTY0NDYzOX0.BQl6-qAPKj6og__6ipuMdejDMqw4z-2-AMicsp5tyf4
###

### ✅ GET - Une commande par ID
GET http://localhost:1992/api/commande/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjExLCJlbWFpbCI6InNhYnJpbmFoXzM4QGhvdG1haWwuZnIiLCJpZF9yb2xlIjoxLCJpYXQiOjE3NDU2ODU0NjUsImV4cCI6MTc0NTc3MTg2NX0.uD9SEQ07TqmO_qrkLeMz0dzgxKv7nnQXc5j-pug5Hyg

###

### ✅ POST - Créer une commande (à partir des lignes du panier) A VOIR SI ON CONSERVE JE NE PENSE PAS
POST http://localhost:1992/api/commande/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjgsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpZF9yb2xlIjoyLCJpYXQiOjE3NDU1NTgyMzksImV4cCI6MTc0NTY0NDYzOX0.BQl6-qAPKj6og__6ipuMdejDMqw4z-2-AMicsp5tyf4
###
{
  "data": {}
}

###

### ✅ PUT - Modifier le statut d’une commande (admin)
PUT http://localhost:1992/api/commande/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjgsImVtYWlsIjoidXJiYW5oZXJpdGFnZS5wcm9qZWN0Lm1kc0BnbWFpbC5jb20iLCJpZF9yb2xlIjoyLCJpYXQiOjE3NDU2ODU0MTMsImV4cCI6MTc0NTc3MTgxM30.SfaRgt-65aRIAt18GdT4UZh9YlKr5LKdid3fYmYCqNc

{
  "data": {
    "statut_commande": "livre"
  }
}

###

### ✅ DELETE - Supprimer une commande (admin)
DELETE http://localhost:1992/api/commande/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjgsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpZF9yb2xlIjoyLCJpYXQiOjE3NDUyNDQ0NjcsImV4cCI6MTc0NTMzMDg2N30.fzuOeqnjaiIpaGv9CKqtHZzX6HAxoLcwW5kQd8bqzqQ

### ✅ Finaliser - Finalise la commande
POST http://localhost:1992/api/commande/finaliser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjgsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpZF9yb2xlIjoyLCJpYXQiOjE3NDU1NTgyMzksImV4cCI6MTc0NTY0NDYzOX0.BQl6-qAPKj6og__6ipuMdejDMqw4z-2-AMicsp5tyf4
###

### 🧪 TEST - Valider le paiement (ex : commande ID 1)
POST http://localhost:1992/api/commande/valider-paiement/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjgsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpZF9yb2xlIjoyLCJpYXQiOjE3NDU1NTgyMzksImV4cCI6MTc0NTY0NDYzOX0.BQl6-qAPKj6og__6ipuMdejDMqw4z-2-AMicsp5tyf4
###