###GET client ok
GET http://localhost:1992/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjMsImVtYWlsIjoiZGFsaWxhQGdtYWlsLmNvbSIsImlhdCI6MTc0NTA5MjY4MiwiZXhwIjoxNzQ1MTc5MDgyfQ.nSJq-sJmLczJkjokmh8ud2RWzPxcm20c7npQ7cMkC9g

###
////////////////////////////////////////////////////////

###GET client particulier ok
GET http://localhost:1992/api/auth/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjMsImVtYWlsIjoiZGFsaWxhQGdtYWlsLmNvbSIsImlhdCI6MTc0NTA5MjY4MiwiZXhwIjoxNzQ1MTc5MDgyfQ.nSJq-sJmLczJkjokmh8ud2RWzPxcm20c7npQ7cMkC9g


###
////////////////////////////////////////////////////////

###POST client
POST http://localhost:1992/api/auth/register
Content-Type: application/json

{
    "data": {
        "nom_client": "Hammadi",
        "prenom_client": "Sabrina",
        "civilite": "femme",
        "date_naissance_client": "21/04/1968",
        "adresse_client": "15 rue des Roses",
        "code_postal_client": "38100",
        "ville_client": "Rives",
        "pays_client": "France",
        "mot_de_passe": "kiwi",
        "adresse_mail_client": "sabrrr@gmail.com"
    }
}
###
////////////////////////////////////////////////////////

###PUT client
PUT http://localhost:1992/api/auth/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjMsImVtYWlsIjoiZGFsaWxhQGdtYWlsLmNvbSIsImlhdCI6MTc0NTA5MjY4MiwiZXhwIjoxNzQ1MTc5MDgyfQ.nSJq-sJmLczJkjokmh8ud2RWzPxcm20c7npQ7cMkC9g

{
    "data": {
        "date_naissance_client": "09/10/1993"
    }
}

###
////////////////////////////////////////////////////////

###DELETE client particulier
DELETE http://localhost:1992/api/auth/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9jbGllbnQiOjMsImVtYWlsIjoiZGFsaWxhQGdtYWlsLmNvbSIsImlhdCI6MTc0NTA5MjY4MiwiZXhwIjoxNzQ1MTc5MDgyfQ.nSJq-sJmLczJkjokmh8ud2RWzPxcm20c7npQ7cMkC9g

